// Emoji shown as each tool's "logo", keyed by the tool's Lucide icon name
// (tool.icon.displayName). Rendered by ToolGlyph in place of the line icon.
// Unknown names fall back to a generic tool emoji.
export const TOOL_EMOJI: Record<string, string> = {
  Captions: "💬",
  Clapperboard: "🎬",
  ArrowRightLeft: "🔄",
  ArrowLeftRight: "↔️",
  Languages: "🌐",
  Clock: "⏱️",
  FileDown: "📥",
  SquarePen: "✏️",
  Smartphone: "📱",
  Eraser: "🧽",
  FileText: "📄",
  ListOrdered: "🔢",
  Globe: "🌍",
  Type: "🔤",
  RefreshCw: "🔄",
  Terminal: "⌨️",
  Music: "🎵",
  Video: "📹",
  Image: "🖼️",
  Code: "💻",
  Sparkles: "✨",
  Braces: "🧩",
  FileJson: "📋",
  FileCode: "📃",
  FileSpreadsheet: "📊",
  Binary: "🔢",
  Link2: "🔗",
  KeyRound: "🔑",
  Lock: "🔒",
  Regex: "🔍",
  Hash: "#️⃣",
  Minimize2: "🗜️",
  WandSparkles: "🪄",
  Wrench: "🔧",
  FileImage: "🖼️",
  Crop: "✂️",
  RotateCw: "🔁",
  Scaling: "📐",
  Shrink: "🗜️",
  Contrast: "🌗",
  SpellCheck: "✍️",
  Mail: "✉️",
  ShoppingBag: "🛍️",
  Smile: "😊",
  Tags: "🏷️",
  Calculator: "🧮",
  Files: "🗂️",
  Scissors: "✂️",
  Palette: "🎨",
  Ruler: "📏",
  Fingerprint: "🕵️",
  ShieldCheck: "🛡️",
  Combine: "➕",
  Volume2: "🔊",
  Gauge: "🚀",
  Film: "🎞️",
  QrCode: "🔳",
  Archive: "🗄️",
  FileArchive: "📦",
  PenLine: "🖊️",
  BookOpen: "📖",
  ScanSearch: "🔎",
  FileSignature: "✒️",
};

export function toolEmoji(iconName: string | undefined | null): string {
  return (iconName && TOOL_EMOJI[iconName]) || "🛠️";
}
