// File-type badge icon system (iLovePDF-style) — data side.
//
// Every tool renders as either:
//   • a CONVERSION icon: source format badge + target format badge + arrow
//     (e.g. PDF → W for "PDF to Word"), or
//   • an OPERATION icon: one format badge + a small action glyph bubble
//     (e.g. PDF + merge arrows for "Merge PDF").
//
// Specs are keyed by tool slug; unknown slugs fall back to a per-category
// default. Rendering lives in components/tools/ToolGlyph.tsx.

export type FormatDef = { label: string; bg: string };

// Colours follow real file-type conventions where one exists (PDF red,
// Word blue, Excel green, HTML orange…) so the badges read instantly.
export const FORMATS = {
  PDF: { label: "PDF", bg: "#E5252A" },
  W: { label: "W", bg: "#185ABD" },
  X: { label: "X", bg: "#107C41" },
  TXT: { label: "TXT", bg: "#64748B" },
  MD: { label: "MD", bg: "#1F2937" },
  HTML: { label: "HTML", bg: "#E44D26" },
  CSS: { label: "CSS", bg: "#2965F1" },
  CODE: { label: "</>", bg: "#334155" },
  JSON: { label: "JSON", bg: "#CA8A04" },
  CSV: { label: "CSV", bg: "#16A34A" },
  XML: { label: "XML", bg: "#0D9488" },
  YML: { label: "YML", bg: "#8B5CF6" },
  SQL: { label: "SQL", bg: "#0369A1" },
  B64: { label: "B64", bg: "#52525B" },
  URL: { label: "URL", bg: "#2563EB" },
  JWT: { label: "JWT", bg: "#C026D3" },
  REGEX: { label: ".*", bg: "#334155" },
  IMG: { label: "IMG", bg: "#57534E" },
  JPG: { label: "JPG", bg: "#D97706" },
  PNG: { label: "PNG", bg: "#0284C7" },
  WEBP: { label: "WEBP", bg: "#7C3AED" },
  GIF: { label: "GIF", bg: "#EC4899" },
  HEIC: { label: "HEIC", bg: "#475569" },
  AVIF: { label: "AVIF", bg: "#9333EA" },
  ICO: { label: "ICO", bg: "#4F46E5" },
  SVG: { label: "SVG", bg: "#EA580C" },
  VID: { label: "VID", bg: "#6D28D9" },
  MP4: { label: "MP4", bg: "#6D28D9" },
  MOV: { label: "MOV", bg: "#4F46E5" },
  WEBM: { label: "WEBM", bg: "#059669" },
  AUD: { label: "AUD", bg: "#BE185D" },
  MP3: { label: "MP3", bg: "#BE185D" },
  WAV: { label: "WAV", bg: "#9D174D" },
  M4A: { label: "M4A", bg: "#A21CAF" },
  SRT: { label: "SRT", bg: "#4F46E5" },
  VTT: { label: "VTT", bg: "#0891B2" },
  ASS: { label: "ASS", bg: "#7C3AED" },
  ZIP: { label: "ZIP", bg: "#B45309" },
  FILE: { label: "FILE", bg: "#57534E" },
  KEY: { label: "KEY", bg: "#E11D48" },
  SSH: { label: "SSH", bg: "#334155" },
  SSL: { label: "SSL", bg: "#15803D" },
  SHA: { label: "SHA", bg: "#52525B" },
  AT: { label: "@", bg: "#0284C7" },
  QR: { label: "QR", bg: "#111827" },
  BAR: { label: "BAR", bg: "#111827" },
  TTF: { label: "TTF", bg: "#334155" },
  WOFF: { label: "WOFF", bg: "#6D28D9" },
  EUR: { label: "€", bg: "#2563EB" },
  USD: { label: "$", bg: "#16A34A" },
  PCT: { label: "%", bg: "#E11D48" },
  EQ: { label: "=", bg: "#64748B" },
  AA: { label: "Aa", bg: "#4F46E5" },
  HEX: { label: "#", bg: "#7C3AED" },
  BIN: { label: "01", bg: "#334155" },
  ROM: { label: "XII", bg: "#92400E" },
  UTC: { label: "UTC", bg: "#0284C7" },
  UNIX: { label: "UNIX", bg: "#334155" },
  KG: { label: "kg", bg: "#D97706" },
  ID: { label: "ID", bg: "#4F46E5" },
  CV: { label: "CV", bg: "#185ABD" },
  VCF: { label: "VCF", bg: "#0891B2" },
  STAR: { label: "✱", bg: "#475569" },
} as const satisfies Record<string, FormatDef>;

export type FormatKey = keyof typeof FORMATS;

export type OpKey =
  | "merge" | "split" | "compress" | "rotate" | "flip" | "pencil" | "pen"
  | "lock" | "key" | "shield" | "shieldX" | "drop" | "eraser" | "globe"
  | "clock" | "sparkle" | "bolt" | "wand" | "scissors" | "crop" | "ruler"
  | "search" | "eyeOff" | "check" | "plus" | "hash" | "tag" | "doc" | "book"
  | "mail" | "card" | "receipt" | "mic" | "music" | "volume" | "gauge"
  | "image" | "camera" | "palette" | "contrast" | "grid" | "diff" | "scan"
  | "link" | "phone" | "sliders" | "smile" | "qr" | "barcode" | "eq" | "quote";

export type ToolIconSpec =
  | { kind: "convert"; from: FormatKey; to: FormatKey }
  | { kind: "op"; badge: FormatKey; op: OpKey };

const c = (from: FormatKey, to: FormatKey): ToolIconSpec => ({ kind: "convert", from, to });
const o = (badge: FormatKey, op: OpKey): ToolIconSpec => ({ kind: "op", badge, op });

/** Per-tool icon spec, keyed by slug. */
export const TOOL_ICON_SPECS: Record<string, ToolIconSpec> = {
  // ── Subtitles ────────────────────────────────────────────────────────────
  "subtitle-generator": c("VID", "SRT"),
  "add-subtitles-to-video": c("SRT", "VID"),
  "srt-to-vtt": c("SRT", "VTT"),
  "vtt-to-srt": c("VTT", "SRT"),
  "translate-subtitles": o("SRT", "globe"),
  "sync-subtitles": o("SRT", "clock"),
  "extract-subtitles": c("VID", "SRT"),
  "subtitle-editor": o("SRT", "pencil"),
  "tiktok-subtitles": o("SRT", "bolt"),
  "clean-subtitles": o("SRT", "eraser"),
  "srt-to-text": c("SRT", "TXT"),
  "youtube-chapters": o("VID", "doc"),
  "batch-translate": o("SRT", "grid"),
  "style-subtitles": c("SRT", "ASS"),
  "auto-sync": o("SRT", "sparkle"),
  // ── Documents / PDF ──────────────────────────────────────────────────────
  "merge-pdf": o("PDF", "merge"),
  "split-pdf": o("PDF", "split"),
  "compress-pdf": o("PDF", "compress"),
  "rotate-pdf": o("PDF", "rotate"),
  "watermark-pdf": o("PDF", "drop"),
  "organize-pdf": o("PDF", "grid"),
  "extract-pdf-pages": o("PDF", "scissors"),
  "pdf-page-numbers": o("PDF", "hash"),
  "edit-pdf-metadata": o("PDF", "tag"),
  "compare-pdf": o("PDF", "diff"),
  "pdf-to-jpg": c("PDF", "JPG"),
  "pdf-to-text": c("PDF", "TXT"),
  "images-to-pdf": c("IMG", "PDF"),
  "markdown-to-word": c("MD", "W"),
  "pdf-redaction": o("PDF", "eyeOff"),
  "resume-builder": o("CV", "plus"),
  "cover-letter": o("W", "mail"),
  "contract-analyzer": o("PDF", "search"),
  "image-to-table": c("IMG", "X"),
  "translate-document-with-layout": o("PDF", "globe"),
  "fill-pdf-form": o("PDF", "pencil"),
  "sign-pdf": o("PDF", "pen"),
  "pdf-ocr": o("PDF", "scan"),
  // ── Images ───────────────────────────────────────────────────────────────
  "remove-background": o("IMG", "eraser"),
  "change-background": o("IMG", "wand"),
  "blur-face": o("IMG", "eyeOff"),
  "flip-image": o("IMG", "flip"),
  "adjust-image": o("IMG", "sliders"),
  "enhance-image": o("IMG", "sparkle"),
  "photo-editor": o("IMG", "pencil"),
  "meme-generator": o("IMG", "smile"),
  "watermark-image": o("IMG", "drop"),
  "image-collage": o("IMG", "grid"),
  "extract-colors": o("IMG", "palette"),
  "compress-image": o("IMG", "compress"),
  "crop-image": o("IMG", "crop"),
  "resize-image": o("IMG", "ruler"),
  "rotate-image": o("IMG", "rotate"),
  "social-media-crop": o("IMG", "phone"),
  "grayscale-image": o("IMG", "contrast"),
  "exif-viewer": o("IMG", "search"),
  "image-to-jpg": c("IMG", "JPG"),
  "image-from-jpg": c("JPG", "PNG"),
  "jpg-to-png": c("JPG", "PNG"),
  "png-to-jpg": c("PNG", "JPG"),
  "jpg-to-webp": c("JPG", "WEBP"),
  "png-to-webp": c("PNG", "WEBP"),
  "webp-to-png": c("WEBP", "PNG"),
  "webp-to-jpg": c("WEBP", "JPG"),
  "svg-to-png": c("SVG", "PNG"),
  "heic-to-jpg": c("HEIC", "JPG"),
  "heic-to-png": c("HEIC", "PNG"),
  "avif-to-jpg": c("AVIF", "JPG"),
  "avif-to-png": c("AVIF", "PNG"),
  "image-to-ico": c("IMG", "ICO"),
  "images-to-gif": c("IMG", "GIF"),
  "html-to-image": c("HTML", "IMG"),
  "image-to-text": c("IMG", "TXT"),
  "handwriting-to-text": c("IMG", "TXT"),
  "image-to-base64": c("IMG", "B64"),
  // ── Video ────────────────────────────────────────────────────────────────
  "compress-video": o("VID", "compress"),
  "trim-video": o("VID", "scissors"),
  "resize-video": o("VID", "ruler"),
  "rotate-video": o("VID", "rotate"),
  "change-video-speed": o("VID", "gauge"),
  "add-watermark": o("VID", "drop"),
  "remove-video-background": o("VID", "eraser"),
  "video-thumbnail": o("VID", "image"),
  "video-screenshot": o("VID", "camera"),
  "mp4-to-gif": c("MP4", "GIF"),
  "gif-to-mp4": c("GIF", "MP4"),
  "mp4-to-mov": c("MP4", "MOV"),
  "mp4-to-webm": c("MP4", "WEBM"),
  "optimize-gif": o("GIF", "compress"),
  "audio-to-video": c("MP3", "MP4"),
  // ── Audio ────────────────────────────────────────────────────────────────
  "audio-from-video": c("VID", "MP3"),
  "compress-audio": o("AUD", "compress"),
  "cut-audio": o("AUD", "scissors"),
  "merge-audio": o("AUD", "merge"),
  "change-volume": o("AUD", "volume"),
  "change-speed": o("AUD", "gauge"),
  "change-audio-pitch": o("AUD", "music"),
  "mp3-to-wav": c("MP3", "WAV"),
  "wav-to-mp3": c("WAV", "MP3"),
  "m4a-to-mp3": c("M4A", "MP3"),
  "voice-to-text": c("AUD", "TXT"),
  // ── Developer ────────────────────────────────────────────────────────────
  "format-json": o("JSON", "check"),
  "format-sql": o("SQL", "check"),
  "minify-css": o("CSS", "compress"),
  "regex-tester": o("REGEX", "search"),
  "json-to-csv": c("JSON", "CSV"),
  "csv-to-json": c("CSV", "JSON"),
  "json-to-xml": c("JSON", "XML"),
  "xml-to-json": c("XML", "JSON"),
  "json-to-yaml": c("JSON", "YML"),
  "yaml-to-json": c("YML", "JSON"),
  "markdown-to-html": c("MD", "HTML"),
  "html-to-markdown": c("HTML", "MD"),
  "excel-to-json": c("X", "JSON"),
  "sql-to-json": c("SQL", "JSON"),
  "json-to-sql": c("JSON", "SQL"),
  "merge-csv": o("CSV", "merge"),
  "base64": o("B64", "flip"),
  "url-encode": o("URL", "flip"),
  "jwt-decoder": o("JWT", "key"),
  "screenshot-to-code": c("IMG", "HTML"),
  // ── Text & AI ────────────────────────────────────────────────────────────
  "word-counter": o("TXT", "hash"),
  "clean-ai-export": o("TXT", "eraser"),
  "anonymize-text": o("TXT", "eyeOff"),
  "translate-text": o("TXT", "globe"),
  "detect-language": o("TXT", "search"),
  "fix-grammar": o("TXT", "check"),
  "rephrase-text": o("TXT", "rotate"),
  "simplify-text": o("TXT", "sparkle"),
  "summarize-text": o("TXT", "compress"),
  "sentiment-analysis": o("TXT", "smile"),
  "hashtag-generator": o("TXT", "hash"),
  "keyword-extractor": o("TXT", "tag"),
  "product-description": o("TXT", "sparkle"),
  "professional-email": o("TXT", "mail"),
  "synonyms-finder": o("TXT", "book"),
  "conjugation": o("TXT", "book"),
  "context-examples": o("TXT", "quote"),
  "citation-generator": o("TXT", "quote"),
  "ai-detector": o("TXT", "scan"),
  // ── Security ─────────────────────────────────────────────────────────────
  "password-checker": o("KEY", "shield"),
  "password-generator": o("KEY", "plus"),
  "ssh-key-generator": o("SSH", "key"),
  "text-encryptor": o("TXT", "lock"),
  "file-encryptor": o("FILE", "lock"),
  "hash-generator": o("SHA", "hash"),
  "email-checker": o("AT", "shield"),
  "phishing-detector": o("URL", "shieldX"),
  "ssl-checker": o("SSL", "lock"),
  "url-scanner": o("URL", "search"),
  // ── Archives ─────────────────────────────────────────────────────────────
  "create-zip": c("FILE", "ZIP"),
  "extract-zip": c("ZIP", "FILE"),
  // ── Utilities ────────────────────────────────────────────────────────────
  "qr-generator": o("QR", "plus"),
  "qr-code-reader": o("QR", "search"),
  "barcode-generator": o("BAR", "barcode"),
  "barcode-reader": o("BAR", "search"),
  "url-shortener": o("URL", "link"),
  "deep-link": o("URL", "phone"),
  "magic-link": o("URL", "sparkle"),
  "link-builder": o("URL", "plus"),
  "utm-builder": o("URL", "tag"),
  "font-converter": c("TTF", "WOFF"),
  "business-card-scanner": o("IMG", "card"),
  "receipt-scanner": o("IMG", "receipt"),
  "invoice-generator": o("PDF", "receipt"),
  "email-signature-generator": o("AT", "pen"),
  "case-converter": o("AA", "flip"),
  "text-diff": o("TXT", "diff"),
  "lorem-ipsum": o("TXT", "doc"),
  "color-converter": o("HEX", "flip"),
  "color-palette-generator": o("HEX", "palette"),
  "currency-converter": c("EUR", "USD"),
  "unit-converter": o("KG", "flip"),
  "number-base-converter": o("BIN", "flip"),
  "roman-numeral-converter": o("ROM", "flip"),
  "timezone-converter": o("UTC", "globe"),
  "unix-timestamp": o("UNIX", "clock"),
  "cron-builder": o("STAR", "clock"),
  "uuid-generator": o("ID", "plus"),
  "percentage-calculator": o("PCT", "eq"),
  "vat-calculator": o("PCT", "receipt"),
  "tip-calculator": o("EUR", "plus"),
  "loan-calculator": o("EUR", "eq"),
  "age-calculator": o("EQ", "clock"),
  "bmi-calculator": o("EQ", "gauge"),
};

/** Category fallback for tools without an explicit spec. */
export const CATEGORY_FALLBACK: Record<string, ToolIconSpec> = {
  subtitles: o("SRT", "sparkle"),
  documents: o("PDF", "doc"),
  images: o("IMG", "image"),
  video: o("VID", "camera"),
  audio: o("AUD", "music"),
  developer: o("CODE", "check"),
  "text-ai": o("TXT", "sparkle"),
  security: o("KEY", "shield"),
  utilities: o("STAR", "plus"),
  archives: o("ZIP", "doc"),
};

const GENERIC: ToolIconSpec = o("FILE", "plus");

export function iconSpecFor(slug?: string | null, category?: string | null): ToolIconSpec {
  return (slug && TOOL_ICON_SPECS[slug]) || (category && CATEGORY_FALLBACK[category]) || GENERIC;
}
