/** "Konvertools vs <competitor>" comparison pages — high-intent switching traffic.
 *  Honest by design: every page includes a "When <competitor> is the better
 *  pick" section, which reads as credible and ranks better.
 */
export type VsRow = { feature: string; konver: string; them: string; win: boolean };
export type Vs = {
  id: string;
  competitor: string;
  hero: string;
  metaTitle: string;
  metaDescription: string;
  intro: string;
  rows: VsRow[];
  better: string[];
  whenThem: string;
  ctaSlugs: string[];
};

export const VS: Record<string, Vs> = {
  ilovepdf: {
    id: "ilovepdf",
    competitor: "iLovePDF",
    hero: "Konvertools vs iLovePDF — More Tools, Free AI, No Ads",
    metaTitle: "Konvertools vs iLovePDF — More Tools, Free AI, No Ads | Konvertools",
    metaDescription: "Konvertools vs iLovePDF compared: 98+ tools beyond PDF, free AI text & subtitle tools, no ads on the free tier, and most processing runs in your browser.",
    intro: "iLovePDF is a solid PDF suite. Konvertools covers PDF too — merge, split, compress, convert — and adds images, audio, video, code, subtitles and AI text tools, with most processing happening right in your browser.",
    rows: [
      { feature: "Price (paid)", konver: "€25/mo Pro", them: "~€7/mo Premium", win: false },
      { feature: "Free tier", konver: "All browser tools, unlimited", them: "Limited tasks/day", win: true },
      { feature: "Tool count", konver: "98+ across 9 categories", them: "~25, PDF-focused", win: true },
      { feature: "Ads on free", konver: "None", them: "Yes", win: true },
      { feature: "AI tools", konver: "Transcribe, translate, rephrase…", them: "Limited", win: true },
      { feature: "Languages", konver: "13-language UI", them: "Multi-language", win: false },
      { feature: "Runs in browser", konver: "Most tools, no upload", them: "Server-side", win: true },
      { feature: "GDPR", konver: "Files deleted in ≤30 min", them: "Deleted after a few hours", win: true },
    ],
    better: [
      "Far more than PDF — images, audio, video, code, subtitles and AI text in one place.",
      "The free tier is genuinely unlimited for browser-side tools, with no ads.",
      "Most conversions never leave your device, so they're instant and private.",
    ],
    whenThem: "iLovePDF has a polished mobile app and desktop app, and some advanced PDF-specific features (OCR, signatures) that Konvertools doesn't offer yet. If you live entirely in PDFs and want native apps, it's a fair choice.",
    ctaSlugs: ["merge-pdf", "pdf-to-jpg", "pdf-to-text"],
  },
  convertio: {
    id: "convertio",
    competitor: "Convertio",
    hero: "Konvertools vs Convertio — Faster, Free, No File Limits",
    metaTitle: "Konvertools vs Convertio — Faster, Free, No File Limits | Konvertools",
    metaDescription: "Konvertools vs Convertio compared: browser-side conversions with no upload, no daily minute caps on free browser tools, plus AI text and subtitle tools.",
    intro: "Convertio converts hundreds of formats on its servers. Konvertools converts the most-used formats right in your browser — so there's no upload, no queue, and no per-day minute cap on the free browser tools.",
    rows: [
      { feature: "Price (paid)", konver: "€25/mo Pro", them: "from $9.99/mo", win: false },
      { feature: "Free tier", konver: "Unlimited browser tools", them: "10 conversions/day, 100 MB", win: true },
      { feature: "Upload required", konver: "No for most tools", them: "Yes, always", win: true },
      { feature: "Speed", konver: "Instant (local)", them: "Upload + queue", win: true },
      { feature: "AI tools", konver: "Yes", them: "No", win: true },
      { feature: "Format breadth", konver: "Common formats", them: "300+ formats", win: false },
      { feature: "Privacy", konver: "Files stay on device", them: "Uploaded to servers", win: true },
    ],
    better: [
      "Browser-side means no upload wait and nothing leaves your device.",
      "No 10-per-day cap or file-size wall on the free browser tools.",
      "AI text and subtitle tools Convertio simply doesn't have.",
    ],
    whenThem: "Convertio supports an enormous long tail of niche formats (CAD, ebooks, fonts, archives) that a browser can't decode. For an exotic format conversion, it's the better tool.",
    ctaSlugs: ["png-to-jpg", "mp4-to-gif", "json-to-csv"],
  },
  smallpdf: {
    id: "smallpdf",
    competitor: "Smallpdf",
    hero: "Konvertools vs Smallpdf — Free Forever, No Sign-up Needed",
    metaTitle: "Konvertools vs Smallpdf — Free Forever, No Sign-up | Konvertools",
    metaDescription: "Konvertools vs Smallpdf compared: no sign-up to use the tools, unlimited free browser-side PDF and conversion tools, plus AI and subtitle tools Smallpdf lacks.",
    intro: "Smallpdf is a clean PDF toolkit that nudges you to sign up and caps free use. Konvertools's browser tools are free and unlimited with no account, and the catalogue goes well beyond PDF.",
    rows: [
      { feature: "Price (paid)", konver: "€25/mo Pro", them: "~€12/mo", win: false },
      { feature: "Sign-up to use", konver: "Never", them: "Pushed / required", win: true },
      { feature: "Free limit", konver: "Unlimited browser tools", them: "2 docs/day", win: true },
      { feature: "Tool breadth", konver: "98+ across 9 categories", them: "PDF + a few", win: true },
      { feature: "AI tools", konver: "Yes", them: "Limited", win: true },
      { feature: "Runs in browser", konver: "Most tools", them: "Server-side", win: true },
      { feature: "GDPR", konver: "Deleted ≤30 min", them: "Deleted after 1h", win: true },
    ],
    better: [
      "No account and no daily document cap on browser tools.",
      "One site for PDF, images, audio, video, code and AI text.",
      "Most tools run locally — faster and more private.",
    ],
    whenThem: "Smallpdf has e-signatures, a desktop app and tight Dropbox/Drive integrations. If you need legally-tracked signing or cloud-storage hooks, it wins there.",
    ctaSlugs: ["pdf-to-jpg", "split-pdf", "pdf-to-text"],
  },
  "adobe-acrobat": {
    id: "adobe-acrobat",
    competitor: "Adobe Acrobat",
    hero: "Konvertools vs Adobe Acrobat — Free Alternative Online",
    metaTitle: "Konvertools vs Adobe Acrobat — Free Online Alternative | Konvertools",
    metaDescription: "Konvertools vs Adobe Acrobat compared: a free, no-install, browser-based alternative for the everyday PDF jobs — merge, split, compress, convert — plus much more.",
    intro: "Adobe Acrobat is the professional standard, with a price to match. For the everyday jobs — merge, split, compress, convert, watermark, page numbers — Konvertools does them free in your browser with nothing to install.",
    rows: [
      { feature: "Price", konver: "Free / €25/mo Pro", them: "~€19/mo", win: false },
      { feature: "Install", konver: "None — web", them: "Desktop app", win: true },
      { feature: "Everyday PDF jobs", konver: "Yes, free", them: "Yes, paid", win: true },
      { feature: "Runs in browser", konver: "Yes, no upload", them: "App / cloud", win: true },
      { feature: "Editing/OCR/forms", konver: "Limited", them: "Full", win: false },
      { feature: "e-Signatures", konver: "No", them: "Yes", win: false },
      { feature: "Beyond PDF", konver: "Images, AV, code, AI", them: "PDF-centric", win: true },
    ],
    better: [
      "Zero cost and zero install for the 90% of tasks people actually do.",
      "Browser-side processing keeps documents private.",
      "A whole conversion suite alongside the PDF tools.",
    ],
    whenThem: "Acrobat Pro is unmatched for deep PDF editing, OCR, fillable forms, redaction and compliant e-signatures. For professional document workflows, it's worth the price.",
    ctaSlugs: ["merge-pdf", "pdf-to-jpg", "watermark-pdf"],
  },
  zamzar: {
    id: "zamzar",
    competitor: "Zamzar",
    hero: "Konvertools vs Zamzar — Faster Conversions, No Email Required",
    metaTitle: "Konvertools vs Zamzar — Faster, No Email Required | Konvertools",
    metaDescription: "Konvertools vs Zamzar compared: instant browser-side conversions with no email and no upload wait, plus AI text and subtitle tools Zamzar doesn't offer.",
    intro: "Zamzar emails you a download link after a server conversion. Konvertools converts the common formats instantly in your browser — no email, no upload, no waiting room.",
    rows: [
      { feature: "Price (paid)", konver: "€25/mo Pro", them: "from $9/mo", win: false },
      { feature: "Free tier", konver: "Unlimited browser tools", them: "Limited, watermarked", win: true },
      { feature: "Email required", konver: "Never", them: "Often for free", win: true },
      { feature: "Upload required", konver: "No for most tools", them: "Yes, always", win: true },
      { feature: "Speed", konver: "Instant (local)", them: "Upload + email", win: true },
      { feature: "AI tools", konver: "Yes", them: "No", win: true },
      { feature: "Format breadth", konver: "Common formats", them: "1,000+ formats", win: false },
    ],
    better: [
      "No email hand-off — your result appears immediately.",
      "Browser-side conversions mean nothing is uploaded and nothing waits in a queue.",
      "AI transcription, translation and text tools Zamzar has no equivalent for.",
    ],
    whenThem: "Zamzar's headline is breadth — over a thousand format pairs including CAD, ebooks and legacy office formats a browser can't touch. For an obscure one-off conversion, it's the safer bet.",
    ctaSlugs: ["png-to-jpg", "mp3-to-wav", "pdf-to-text"],
  },
  cloudconvert: {
    id: "cloudconvert",
    competitor: "CloudConvert",
    hero: "Konvertools vs CloudConvert — Free Alternative, No Credits",
    metaTitle: "Konvertools vs CloudConvert — Free, No Credits | Konvertools",
    metaDescription: "Konvertools vs CloudConvert compared: no per-conversion credit system on free browser tools, instant local processing, plus AI text and subtitle tools.",
    intro: "CloudConvert meters everything with a credit/minute system. Konvertools's browser tools are free and uncounted — the credits only exist for the optional REST API.",
    rows: [
      { feature: "Pricing model", konver: "Free browser tools; API credits optional", them: "Credits/minutes for everything", win: true },
      { feature: "Free tier", konver: "Unlimited browser tools", them: "25 conversions/day", win: true },
      { feature: "Upload required", konver: "No for most tools", them: "Yes, always", win: true },
      { feature: "Speed", konver: "Instant (local)", them: "Upload + queue", win: true },
      { feature: "AI tools", konver: "Yes", them: "No", win: true },
      { feature: "API", konver: "Yes, pay-as-you-go", them: "Yes, robust", win: false },
      { feature: "Format breadth", konver: "Common formats", them: "200+ formats", win: false },
    ],
    better: [
      "No credit accounting for everyday browser conversions.",
      "Local processing — faster and fully private.",
      "Built-in AI text and subtitle tools.",
    ],
    whenThem: "CloudConvert has a mature, well-documented API with deep format coverage and per-job options. For heavy server-side automation across many exotic formats, it's a strong platform.",
    ctaSlugs: ["compress-video", "mp4-to-webm", "json-to-yaml"],
  },
  veed: {
    id: "veed",
    competitor: "VEED",
    hero: "Konvertools vs VEED — Free Video & Subtitle Tools",
    metaTitle: "Konvertools vs VEED — Free Video & Subtitle Tools | Konvertools",
    metaDescription: "Konvertools vs VEED compared: free, watermark-free subtitle generation, translation and quick video edits in your browser, without a full editor or subscription.",
    intro: "VEED is a full online video editor. If you mainly need subtitles, audio extraction and quick edits, Konvertools does those free in your browser — and adds PDF, image, code and AI text tools.",
    rows: [
      { feature: "Price (paid)", konver: "€25/mo Pro", them: "from ~$18/mo", win: false },
      { feature: "Free watermark", konver: "Only on burned-in subs (free)", them: "Yes, on exports", win: true },
      { feature: "Subtitle generation", konver: "AI, 30+ languages", them: "AI, yes", win: false },
      { feature: "Full timeline editor", konver: "No (focused tools)", them: "Yes", win: false },
      { feature: "Beyond video", konver: "PDF, images, code, AI text", them: "Video-centric", win: true },
      { feature: "Runs in browser", konver: "Yes, no upload", them: "Cloud", win: true },
      { feature: "Sign-up to use", konver: "No", them: "Yes", win: true },
    ],
    better: [
      "Subtitles, translation and audio extraction without a heavy editor.",
      "No account needed, and most tools run locally.",
      "A whole conversion suite beyond video.",
    ],
    whenThem: "VEED is a genuine timeline editor with multi-track editing, brand kits, screen recording and team collaboration. For real video production, it's the right tool.",
    ctaSlugs: ["subtitle-generator", "add-subtitles-to-video", "audio-from-video"],
  },
  kapwing: {
    id: "kapwing",
    competitor: "Kapwing",
    hero: "Konvertools vs Kapwing — Free Online Media Tools",
    metaTitle: "Konvertools vs Kapwing — Free Online Media Tools | Konvertools",
    metaDescription: "Konvertools vs Kapwing compared: free, no-watermark conversion and subtitle tools that run in your browser, without a collaborative editor or subscription.",
    intro: "Kapwing is a collaborative content studio. For the conversion and subtitle jobs around your content, Konvertools is free, browser-side and watermark-free on text outputs.",
    rows: [
      { feature: "Price (paid)", konver: "€25/mo Pro", them: "from ~$16/mo", win: false },
      { feature: "Free watermark", konver: "Only on burned-in subs", them: "Yes", win: true },
      { feature: "Tool breadth", konver: "98+ across 9 categories", them: "Media studio", win: true },
      { feature: "Full editor", konver: "No (focused tools)", them: "Yes", win: false },
      { feature: "Runs in browser", konver: "Most tools, no upload", them: "Cloud", win: true },
      { feature: "AI text tools", konver: "Yes", them: "Some", win: true },
      { feature: "Sign-up to use", konver: "No", them: "Yes", win: true },
    ],
    better: [
      "Conversions and subtitles without a studio or an account.",
      "Most processing is local, so it's instant and private.",
      "Covers documents, images, audio, video, code and AI text in one place.",
    ],
    whenThem: "Kapwing shines for collaborative, template-driven social content with a timeline, team workspaces and a huge asset library. For content creation, it's purpose-built.",
    ctaSlugs: ["subtitle-generator", "mp4-to-gif", "resize-image"],
  },
  reverso: {
    id: "reverso",
    competitor: "Reverso",
    hero: "Konvertools vs Reverso — AI Rephraser + Translation Free",
    metaTitle: "Konvertools vs Reverso — AI Rephraser + Translation | Konvertools",
    metaDescription: "Konvertools vs Reverso compared: AI translation, rephrasing, summarizing and grammar in 30+ languages — plus a full conversion suite Reverso doesn't have.",
    intro: "Reverso is great for translation and language learning. Konvertools covers translation too, adds rephrasing, summarizing, grammar and humanizing — and a whole file-conversion suite alongside.",
    rows: [
      { feature: "Price (paid)", konver: "€25/mo Pro", them: "from ~$7/mo", win: false },
      { feature: "Translation", konver: "AI, 30+ languages", them: "Yes, with context", win: false },
      { feature: "Rephrase / summarize", konver: "Yes", them: "Limited", win: true },
      { feature: "Subtitle translation", konver: "Cue-by-cue, timed", them: "No", win: true },
      { feature: "Beyond text", konver: "PDF, images, audio, video", them: "Text only", win: true },
      { feature: "Ads on free", konver: "None", them: "Yes", win: true },
      { feature: "API", konver: "Yes", them: "Yes", win: false },
    ],
    better: [
      "Rephrase, summarize, fix grammar and humanize — not just translate.",
      "Translate whole subtitle files keeping the timestamps intact.",
      "Convert files in the same place you polish your text.",
    ],
    whenThem: "Reverso's contextual examples, conjugation tables and language-learning features are excellent. For studying a language or checking nuanced usage, it's hard to beat.",
    ctaSlugs: ["translate-text", "rephrase-text", "translate-subtitles"],
  },
  grammarly: {
    id: "grammarly",
    competitor: "Grammarly",
    hero: "Konvertools vs Grammarly — Free Grammar Checker + More",
    metaTitle: "Konvertools vs Grammarly — Free Grammar Checker + More | Konvertools",
    metaDescription: "Konvertools vs Grammarly compared: free AI grammar fixing, rephrasing and summarizing with no install — plus translation and a full conversion suite.",
    intro: "Grammarly is a polished writing assistant that lives in your browser and apps. Konvertools offers free grammar fixing, rephrasing, summarizing and humanizing on demand — no extension, plus translation and file tools.",
    rows: [
      { feature: "Price (paid)", konver: "€25/mo Pro", them: "from ~$12/mo", win: false },
      { feature: "Free grammar", konver: "Yes, AI", them: "Yes, basic", win: false },
      { feature: "Rephrase / tone", konver: "Yes, several styles", them: "Premium", win: true },
      { feature: "Install / extension", konver: "None — paste & go", them: "Extension/app", win: true },
      { feature: "Translation", konver: "30+ languages", them: "No", win: true },
      { feature: "Beyond writing", konver: "PDF, images, audio, video", them: "Writing only", win: true },
      { feature: "Real-time in every app", konver: "No", them: "Yes", win: false },
    ],
    better: [
      "Rephrase, summarize, humanize and fix grammar with no extension to install.",
      "Translate the same text into 30+ languages right after polishing it.",
      "Everything else you need — convert, compress, transcribe — in one place.",
    ],
    whenThem: "Grammarly's always-on, in-context checking across email, docs and the web — plus its tone and clarity suggestions as you type — is unmatched for daily writing. If you want a live assistant everywhere, install it.",
    ctaSlugs: ["fix-grammar", "rephrase-text", "summarize-text"],
  },
  deepl: {
    id: "deepl",
    competitor: "DeepL",
    hero: "Konvertools vs DeepL — Free Translator with More Tools",
    metaTitle: "Konvertools vs DeepL — Free Translator + More Tools | Konvertools",
    metaDescription: "Konvertools vs DeepL compared: free AI translation in 30+ languages plus subtitle translation, rephrasing and a full conversion suite DeepL doesn't offer.",
    intro: "DeepL is renowned for translation quality. Konvertools translates in 30+ languages too, and adds subtitle translation, rephrasing, summarizing and a complete file-conversion suite.",
    rows: [
      { feature: "Price (paid)", konver: "€25/mo Pro", them: "from ~€8/mo", win: false },
      { feature: "Translation quality", konver: "AI, very strong", them: "Best-in-class", win: false },
      { feature: "Subtitle translation", konver: "Cue-by-cue, timed", them: "Document only", win: true },
      { feature: "Rephrase / summarize", konver: "Yes", them: "Write (separate)", win: true },
      { feature: "Beyond text", konver: "PDF, images, audio, video", them: "Text & docs", win: true },
      { feature: "Free tier", konver: "Daily AI allowance", them: "Char-limited", win: true },
      { feature: "API", konver: "Yes", them: "Yes", win: false },
    ],
    better: [
      "Translate subtitle files cue-by-cue with timestamps preserved.",
      "Rephrase and summarize alongside translation, in one place.",
      "A full conversion suite around your multilingual content.",
    ],
    whenThem: "DeepL still sets the bar for raw translation quality and nuance, especially for European language pairs and formal documents. For translation as your core need, it's exceptional.",
    ctaSlugs: ["translate-text", "translate-subtitles", "subtitle-generator"],
  },
  "remove-bg": {
    id: "remove-bg",
    competitor: "Remove.bg",
    hero: "Konvertools vs Remove.bg — Free Background Remover + More",
    metaTitle: "Konvertools vs Remove.bg — Free Background Remover + More | Konvertools",
    metaDescription: "Konvertools vs Remove.bg compared: free, full-resolution AI background removal that runs in your browser with no credits — plus a full image and conversion suite.",
    intro: "Remove.bg pioneered one-click background removal but meters full-resolution output with credits. Konvertools removes backgrounds free, at full resolution, entirely in your browser — and does much more.",
    rows: [
      { feature: "Price", konver: "Free, full-res", them: "Free preview; credits for HD", win: true },
      { feature: "Full resolution free", konver: "Yes", them: "No (paid)", win: true },
      { feature: "Runs in browser", konver: "Yes, no upload", them: "Server-side", win: true },
      { feature: "Video background", konver: "Yes", them: "Limited", win: true },
      { feature: "Beyond background", konver: "Convert, resize, palette…", them: "Background-centric", win: true },
      { feature: "Raw cut-out quality", konver: "Very good", them: "Excellent", win: false },
      { feature: "API", konver: "Rolling out", them: "Mature", win: false },
    ],
    better: [
      "Full-resolution PNGs for free — no credit wall.",
      "Runs entirely in your browser, so images are never uploaded.",
      "Remove video backgrounds too, plus resize, convert and palette tools.",
    ],
    whenThem: "Remove.bg's model is still a touch sharper on tricky edges like fine hair and fur, and its API is battle-tested at scale. For the highest-fidelity cut-outs or heavy API volume, it's the specialist.",
    ctaSlugs: ["remove-background", "remove-video-background", "extract-colors"],
  },
  "mailgun-validator": {
    id: "mailgun-validator",
    competitor: "Mailgun Email Validation",
    hero: "Konvertools vs Mailgun Email Validation — Free, In-Browser Email Verifier",
    metaTitle: "Konvertools vs Mailgun Email Validation — Free Email Verifier | Konvertools",
    metaDescription: "Konvertools Email Verifier runs the same checks as Mailgun's Email Validation — syntax, domain DNS, MX records, disposable detection — with a free tier and no API key required.",
    intro: "Mailgun's Email Validation API is solid for high-volume B2B list cleaning. Konvertools' Email Verifier covers the same essential signals — syntax, domain resolution, MX records, disposable-provider detection — without an API key or paid plan to get started.",
    rows: [
      { feature: "Syntax check", konver: "Yes", them: "Yes", win: false },
      { feature: "Domain DNS check", konver: "Yes", them: "Yes", win: false },
      { feature: "MX record check", konver: "Yes", them: "Yes", win: false },
      { feature: "Disposable / role detection", konver: "Disposable", them: "Disposable + role", win: false },
      { feature: "SMTP handshake (catch-all)", konver: "No", them: "Yes", win: false },
      { feature: "Free quota", konver: "5/day signed in", them: "100/month then $", win: true },
      { feature: "Pricing", konver: "€25/mo Pro = 500/mo", them: "$0.45/1000 (Foundation)", win: false },
      { feature: "Other tools included", konver: "165+ tools", them: "Email-only product", win: true },
    ],
    better: [
      "Free tier gets you 5 verifications/day without a credit card or API key.",
      "No upload — the address is checked via passive DNS only.",
      "Bundled with virus, URL and phishing scanners under one account.",
    ],
    whenThem: "Mailgun adds an SMTP handshake step that detects catch-all domains and confirms a mailbox truly exists. For high-stakes deliverability work on enterprise lists, that extra signal is worth paying for.",
    ctaSlugs: ["email-checker", "url-scanner", "phishing-detector"],
  },
  urlvoid: {
    id: "urlvoid",
    competitor: "URLVoid",
    hero: "Konvertools vs URLVoid — Free URL & Phishing Link Scanner",
    metaTitle: "Konvertools vs URLVoid — Free URL Scanner Compared | Konvertools",
    metaDescription: "Konvertools URL Scanner checks any link against Google Safe Browsing and adds a Mistral-powered phishing-email analyser — free, no ads, no sign-up.",
    intro: "URLVoid aggregates a dozen reputation services to score a URL. Konvertools' URL Scanner uses Google Safe Browsing (the largest single threat database) and pairs it with an AI-assisted email-text analyser that catches phishing patterns URLVoid can't see in isolation.",
    rows: [
      { feature: "Reputation source", konver: "Google Safe Browsing", them: "~30 RBLs aggregated", win: false },
      { feature: "Phishing email analysis", konver: "Yes — AI + link check", them: "No", win: true },
      { feature: "SSL certificate checker", konver: "Yes", them: "No", win: true },
      { feature: "Email verifier included", konver: "Yes", them: "No", win: true },
      { feature: "Ad-supported", konver: "Light, optional", them: "Heavy ad blocks", win: true },
      { feature: "Free daily limit", konver: "20 URLs/day", them: "Few/IP/day soft cap", win: false },
    ],
    better: [
      "Google Safe Browsing is the broadest single threat dataset — used by Chrome itself.",
      "Bundled with a phishing-email detector that reads the message context, not just the link.",
      "Cleaner, ad-light interface plus SSL, email and password security tools on the same site.",
    ],
    whenThem: "URLVoid's aggregate score across many RBLs surfaces consensus on borderline domains better than any single source. For threat-intel research where you want to see which lists are flagging a site, it's the right tool.",
    ctaSlugs: ["url-scanner", "phishing-detector", "ssl-checker"],
  },
};

export const VS_IDS = Object.keys(VS);
